spring:
  datasource:
    dynamic:
      primary: user
      # 未匹配到数据源时，true抛异常，false使用默认数据源
      strict: true
      datasource:
        user:
          url: jdbc:mysql://127.0.0.1:3306/mall_user?serverTimezone=GMT%2b8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
        goods:
          url: jdbc:mysql://127.0.0.1:3306/mall_goods?serverTimezone=GMT%2b8&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
        promotion:
          url: jdbc:mysql://127.0.0.1:3306/mall_promotion?serverTimezone=GMT%2b8&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
        normal:
          url: jdbc:mysql://127.0.0.1:3306/mall_normal?serverTimezone=GMT%2b8&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
        order:
          url: jdbc:mysql://127.0.0.1:3306/mall_order?serverTimezone=GMT%2b8&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
        cart:
          url: jdbc:mysql://127.0.0.1:3306/mall_cart?serverTimezone=GMT%2b8&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
